### ISSUE TITLE
Need to add ListedItem IDs and Message IDs to corresponding fields in User and ListedItem Types

### ISSUE THREAD

**Issue by ckester99** [beefbones/swapshop#27]
We have a lot of good seed data. The final item before seed data tasks are done is adding filling out the fields in the following Models:

## User 
- [ ] listedItems: Needs to be an array containing all of the item IDs the user has posted
- [ ] messages:  Needs to be an array containing all of the message IDs the user has posted

## ListedItem
- [ ] messages:  Needs to be an array containing all of the message IDs the user has posted

**Comment by kmorrison12** [comment]
arrays have been created
